### ISSUE TITLE
 Error when using where

### ISSUE THREAD

**Issue by idamkiller** [thyyppa/fluent-fm#1]
Whenever the "where" function is used, it returns an error indicating that it does not find the field. Could you tell me how to fix it please?

**Comment by thyyppa** [comment]
Hmm, one thing that could be the issue - filemaker requires that the field is placed on the layout. If it's only part of the database table but not on the layout as well it won't be able to access that field. It's an annoying limitation of the data api, which really only interacts with the layouts as if you were physically behind a desk looking at filemaker.

If that's not the case, could you send me a screenshot of your database table and layout in edit mode? I'll try to recreate the problem.

**Comment by idamkiller** [comment]
Of course, thank you very much for your help
![image](https://user-images.githubusercontent.com/13484697/55402617-8119b600-5519-11e9-954a-79128cc77895.png)
![image](https://user-images.githubusercontent.com/13484697/55402705-af979100-5519-11e9-9962-1c4f81c2b9f1.png)
![image](https://user-images.githubusercontent.com/13484697/55402780-e8d00100-5519-11e9-9f89-514df9460aa9.png)


If I do not use the "where" everything works without problem

**Comment by thyyppa** [comment]
Ah, it looks like your missing the `deleted_at` field that it uses to check for soft deletes. I don't think you absolutely have to have `created _at` or `updated_at` but it's for sure checking `deleted_at`

I wish fmdapi returned more useful error messages in these situations.

**Comment by idamkiller** [comment]
Perfect friend thank you very much I am working excellent

**Comment by thyyppa** [comment]
That's great to hear! Have a great day! :)

**Comment by thyyppa** [comment]
Just an update - I've removed the requirement for the `deleted_at`, `created_at`, and `updated_at` fields. Now all that is needed for basic usage is `id`. 

However, if using soft deletes `deleted_at` is still needed, and for certain sort operations `created_at` and `updated_at` should be included. You can now override the names of all of these fields.
