### ISSUE TITLE
search criteria clearing

### ISSUE THREAD

**Issue by bmangus** [thyyppa/fluent-fm#5]
This is a great package I have used in several projects. Thank you for making it available. I have an issue in one of my projects related to search criteria across multiple uses. As far as I can tell in the documentation, there is no way to clear existing search criteria in a persistent connection. I am using a singleton model where I instantiate the connection in the constructor and use the same instance across several queries and updates throughout my job. The problem is when I try to search for the same foreign key in two different fields. In this use case, I have actual parent with child records. The data model has two foreign key fields, one for the father and one for the mother. I do not always have a 'gender' to use as a qualifier for the search. So I am using a standard try catch to first check for child records where the parent is in the mother fk field. Then do the same for the father fk field position. What I see in the logs is that the search criteria value is persisted from the mother search when the father search is executed. So I never get a correct return from my attempts to search for the father because it is searching for records that have a parent pk in both the father fk and mother fk fields. This breaks down in many other places later on, but in all cases it is related to search criteria persisting after execution. If I am somehow using this incorrectly, please let me know.

**Comment by bmangus** [comment]
I was able to get around this issue by creating my own service container that extends the FluentFMRepository. This allows access to the protected clearQuery method in the BaseConnection class. Anyone else who has this issue simply do the following: create a FileMakerServiceContainer with the following like this:

<img width="523" alt="Screen Shot 2020-02-15 at 4 25 09 PM" src="https://user-images.githubusercontent.com/8528211/74596069-be8f1100-500f-11ea-9fa7-344af9779345.png">

Then in the constructor, you can instantiate the FileMakerServiceContainer and assign it to a public variable for repeated usage. 

<img width="520" alt="Screen Shot 2020-02-15 at 4 28 42 PM" src="https://user-images.githubusercontent.com/8528211/74596102-3c531c80-5010-11ea-9448-44425e3e0fc8.png">

Anytime you want to reset your connection, just call $this-fm-clear();

**Comment by thyyppa** [comment]
Ah, good point! For version 1.1.5 I've opened up `->clearQuery()` and also added a `->reset()` which does basically the same thing. I also have it clearing after fetch operations now, which makes more sense.

Thanks for pointing this out!
